### ISSUE TITLE
Windows and php 7.1

### ISSUE THREAD

**Issue by matjazpotocnik** [Toutouwai/FieldtypeFileUnrenamed#1]
Hi, thanks for the module. I really didn't want to create a module by myself before Ryan say something, unfortunately he didn't respond to the lengthy thread. I haven't tested your module yet, but just to say that you don't need php-wfio on windows if you are on php 7.1. While php-wfio works in my tests (as far as I remember, it's over a year now), I don't think it's worth dealing with it, it's much better to upgrade to the latest php.

**Comment by Toutouwai** [comment]
> Hi, thanks for the module. 

No problem.

> but just to say that you don't need php-wfio on windows if you are on php 7.1

Yes, the module readme says as much.

> I don't think it's worth dealing with it, it's much better to upgrade to the latest php.

I agree, but many people are perhaps not using PHP >= 7.1 and it saves me having to answer questions about why it doesn't work for them.

**Comment by Toutouwai** [comment]
I'll mention the 7.1 thing again in the readme so it's doubly-clear :-)

**Comment by matjazpotocnik** [comment]
> I'll mention the 7.1 thing again in the readme so it's doubly-clear :-)

Thx.

> I agree, but many people are perhaps not using PHP >= 7.1 and it saves me having to answer questions about why it doesn't work for them.

Maybe you could add support for php-wfio, but I guess it's not worth it. Maybe just a warning at install?

`If $sanitizer->text() interferes with special characters in your filenames you will have to add your own custom sanitization to the module.`

Would be nice if we could set this in the module itself or perhaps per Fieldtype? But then again, text method seems just fine, as with the default options only strip_tags() function will be run.

Oh, you went with extending file type. Cool! Now, how I didn't think of that?

**Comment by Toutouwai** [comment]
This module isn't intended as a complete solution for casual users. It won't be going in the modules directory for instance. It's something for other module developers to use as a starting point, just illustrating how you can work around PW default behaviour by extending core classes and overriding methods.

I don't have a need for this functionality myself. Anyone who wants to fork or take over the module is most welcome!

**Comment by matjazpotocnik** [comment]
Ok, I agree. Thanks again for sharing.

**Comment by matjazpotocnik** [comment]
Just tested it on my test files (exactly the same as I used in my testing) and it's working :-)

What I discovered is when you change the field type from File to FileUnrenamed, you have to save the field twice. I believe this behaviour has nothing to do with the module itself.
